### ISSUE TITLE
Update from talk-template

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/project-planning-wireframes-practice#6]
Needs new license notice, license, contributing, style, **etc**. please follow process documentation and use best discretion for which files to add.

**Comment by raq929** [comment]
I updated from `study-template`

**Comment by RealWeeks** [comment]
They typically are the same except for the readme, but it looks like `talk-template` was updated more recently than `study-template`

**Comment by RealWeeks** [comment]
@raq929 please don't close with a commit. Allow the person who opened the issue to close. You can reference it a commit.

**Comment by gaand** [comment]
@J-Weeks I think this is clear now: closing with a commit is allowed by the reviewer agreeing and merging.
